# Generated by Django 5.0.6 on 2024-08-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
